### ISSUE TITLE
Missing work: Hauptsatz for the Theory of Species

### ISSUE THREAD

**Issue by asr** [michaelt/martin-lof#20]
The DOI for the missing work is [this](https://doi.org/10.1016/S0049-237X(08)70848-6).

**Comment by chrisittner** [comment]
Note that you can find that paper in the .pdf file for "Hauptsatz for the intuitionistic theory of iterated inductive definitions" in this repository. 

The [pdf file](https://github.com/michaelt/martin-lof/blob/master/pdfs/Hauptsatz-for-the-intuitionistic-theory-of-iterated-inductive-definitions-1971.pdf) contains both papers, "Hauptsatz for the intuitionistic theory of iterated inductive definitions" being on publication pages 179-216 and then "Hauptsatz for the Theory of Species" on pages 217-233.
