### ISSUE TITLE
"Assertion and Request"

### ISSUE THREAD

**Issue by bblfish** [michaelt/martin-lof#23]
That was a talk given in 2017 or so and it is cited has having been transcribed by Ansten Klev. But I can't find any version of it online.  See [Twitter thread](https://twitter.com/bblfish/status/1241425579611750400) for references.

**Comment by gallais** [comment]
Have you tried emailing Ansten Klev and asking him whether he would be willing
to share his notes (& have them uploaded here, ideally)?

**Comment by mietek** [comment]
Email sent.

**Comment by zacque0** [comment]
Hi, the transcript is now available online at: https://pml.flu.cas.cz/.

**Comment by stevana** [comment]
Added in #36.
