### ISSUE TITLE
Missing paper

### ISSUE THREAD

**Issue by RobertHarper** [michaelt/martin-lof#27]
The typeset version of The Logic of Judgments is currently a 404.  Not sure whether it's a link issue, or whether a PDF is missing?

**Comment by gallais** [comment]
I believe this is https://github.com/michaelt/martin-lof/pull/22#issuecomment-777640406

We should perhaps link to the pdfs stored on this repo (in https://github.com/michaelt/martin-lof/tree/master/pdfs)
rather than via michael's website as it does not seem to be updated anymore.

**Comment by RobertHarper** [comment]
Yes, good idea.  We might also put the .bib file in that directory as well.

(c) Robert Harper.  All Rights Reserved.
