### ISSUE TITLE
underpopulated .bib

### ISSUE THREAD

**Issue by RobertHarper** [michaelt/martin-lof#28]
I've found and added some new entries to the .bib file, but am unable to upload them or to create an issue.  How should I contribute?

**Comment by gallais** [comment]
You should be able to fork the repo (link in the top right corner),
push your changes there and then [open a Pull Request](https://github.com/michaelt/martin-lof/compare).

**Comment by RobertHarper** [comment]
Thanks, done.

(c) Robert Harper.  All Rights Reserved.
