### ISSUE TITLE
Transcripts from talks

### ISSUE THREAD

**Issue by stevana** [michaelt/martin-lof#35]
New website with transcripts from talks: https://pml.flu.cas.cz, all carefully proof read by Per according to Jan Smith (who posted the link).

**Comment by wmacmil** [comment]
but should we just include the URL in the README or should we just upload the pdfs directly to this ?

**Comment by wmacmil** [comment]
i made a branch locally but i don't have rights to push the branch, so I can make a PR.

**Comment by stevana** [comment]
Fixed in #36.
