### ISSUE TITLE
syntax&semantics of primitive recursive functions & "informal notes on foundations" are the same

### ISSUE THREAD

**Issue by jonsterling** [michaelt/martin-lof#8]
Perhaps Dr Hancock knew the provenience of this one better than did Bob Constable? Anyway, these are the same document in any case.

**Comment by michaelt** [comment]
Yes, I wonder what is going on. I had read the file with Constable's annotations before, and figured I must have lost track of it when you added it. (I remember thinking that Constable's date was obviously too early, for one thing.)  But now I see it was renamed.  If it was mislabelled, that would suggest that there is some other manuscript of Martin-Löf and Hancock with the title "Syntax and Semantics ... " that somehow went missing when @stevana  added all the excellent things from Hancock? (This is starting to seem less probable to me as I think about it.) It would be nice in any case to have a cleaner copy.

**Comment by stevana** [comment]
This is what Hank said when he sent me the stuff:

> Somewhere I've a pdf of a preprint that Per and I wrote together.  It might even be in the tar.
> It was called (approximately) "Syntax and semantics of the language of primitive recursive functions".
> I think I got it from somewhere on the nuprl site, maybe from the supporting materials for some
> course.  (I lost my own paper copy decades ago.)

**Comment by michaelt** [comment]
Now that I am looking at it again, it is obvious that the period (1975) is right, given all the references to Dummett in the text. Indeed I might have guessed it is the typescript by Hancock mentioned in the letter to Dummett (1976) in preparation for Dummett's 'Logical Basis of Metaphysics' lectures. But the division into a 'general philosophical introduction, covering the first ten pages', and the rest, doesn't seem to fit this manuscript.

**Comment by michaelt** [comment]
It's seeming clearer and clearer to me that this must be the preprint Hancock was referring to, mislabelled by Constable, rightly labelled by stevena. It is too bad we don't have a cleaner copy. Also too bad that the (1975) lecture notes Martin-Löf refers to, which must be different, are missing. Maybe there is a copy buried amid Dummett's literary remains.
